
# A basic apache server. To use either add or bind mount content under /var/www
ARG  CODE_VERSION=latest
FROM alpine:${CODE_VERSION}

MAINTAINER Bernd Lambertz version: 0.1

RUN apt-get update && apt-get install

CMD ["/bin/bash"]